# Replace the text below to customize your site
site_name: maryamshojaei - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: maryamshojaei  
copyright: Copyleft 2023 "Student Name" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Reflections :
      - Term 1:
          - Design Studio 0: term1/01-Design studio 0.md
          - Design Studio 1: term1/02-Design studio 1.md
          - Reflection I: term1/03-reflection I.md
          - AOWS: term1/04-AWOS.md
          - Unpacking Tech Systems I: term1/05-Unpacking Tech Systems I.md
          - Unpacking Tech Systems II: term1/06-Unpacking Tech Systems II.md
          - Fundamentals for Future Makers: term1/07-Fundamentals for Future Makers.md


      - Term 2:
          - digi: term1/01-Bootcamp.md
          - studio: term1/01-Bootcamp.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette: custom
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
